title: Andy J. Wills
description: Professor of Psychology
remote_theme: IbraheemR/Muzi

logo: /assets/logo_blue.svg

url: https://www.andywills.info

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"



